config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'books#index'
  resources :issuances
  resources :books
  resources :libraries
  resources :subscribers
  resources :workers
  get '/summary', to: 'summary#index', as: :summary

end

app/models/library.rb
class Library < ActiveRecord::Base
  has_many :books, dependent: :destroy
  has_many :workers, dependent: :destroy
  has_many :subscribers, dependent: :destroy
  
  validates :number, :name, :address, presence: true
  validates :number, uniqueness: true
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, :flash => { success: "Библиотека успешно добавлена"} }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, :flash => { success: "Библиотека успешно обновлена"} }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, :flash => { danger: "Библиотека удалена"} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(
        :number,
        :name,
        :address
        )
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library, html: {class: 'form-horizontal'}) do |f| %>
    <% if @library.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>
            <ul>
                <% @library.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>
            <div class="form-group">
                <label for="library[number]" class="col-md-2">Номер</label>
                <div class="col-md-4">
                    <%= f.text_field :number, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="library[name]" class="col-md-2">Наименование</label>
                <div class="col-md-4">
                    <%= f.text_field :name, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="library[address]" class="col-md-2">Адрес</label>
                <div class="col-md-4">
                    <%= f.text_field :address, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <br>
            <div class="actions">
                <%= f.submit "Отправить", class: 'btn btn-sm btn-primary' %>
            </div>
            <% end %>

app/views/libraries/edit.html.erb
<% breadcrumb :edit_library, @library %>
    <h1>Редактирование библиотеки</h1>
    <%= render 'form' %>
        <br>
        <%= link_to @library do %>
            <span>←</span> Назад
            <% end %>

app/views/libraries/index.html.erb
<% breadcrumb :libraries %>
    <div class="row">
        <div class="col-md-6">
            <h1>Библиотеки</h1>
        </div>
        <div class="col-md-6">
            <div class="pull-right">
                <%= link_to new_library_path, class: 'btn btn-primary btn-sm' do %>
                    <i class="fa fa-plus"></i> Новая библиотека
                    <% end %>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="table__id">#</th>
                <th>Номер</th>
                <th>Название</th>
                <th>Адрес</th>
                <th class="table__actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            <% @libraries.each do |library| %>
                <tr>
                    <td class="table__id">
                        <%= library.id %>
                    </td>
                    <td>
                        <%= library.number %>
                    </td>
                    <td>
                        <%= library.name %>
                    </td>
                    <td>
                        <%= library.address %>
                    </td>
                    <td class="table__actions">
                        <%= link_to library do %>
                            <i class="fa fa-eye"></i>
                            <% end %>
                                <%= link_to edit_library_path(library) do %>
                                    <i class="fa fa-pencil"></i>
                                    <% end %>
                                        <%= link_to library, method: :delete, data: { confirm: 'Вы уверены?' } do %>
                                            <i class="fa fa-trash"></i>
                                            <% end %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

app/views/libraries/new.html.erb
<% breadcrumb :new_library %>
    <h1>Новая библиотека</h1>
    <%= render 'form' %>
        <br>
        <%= link_to libraries_path  do %>
            <span>←</span> Назад
            <% end %>

app/views/libraries/show.html.erb
<% breadcrumb :library, @library %>
    <h1><%= @library.name %></h1>
    <div class="row">
        <label for="library[number]" class="col-md-2">Номер</label>
        <div class="col-md-4">
            <%= @library.number %>
        </div>
    </div>
    <div class="row">
        <label for="library[name]" class="col-md-2">Наименование</label>
        <div class="col-md-4">
            <%= @library.name %>
        </div>
    </div>
    <div class="row">
        <label for="library[address]" class="col-md-2">Адрес</label>
        <div class="col-md-4">
            <%= @library.address %>
        </div>
    </div>
    <br>
    <div>
        <%= link_to 'Изменить', edit_library_path(@library), class: 'btn btn-primary btn-sm' %>
    </div>
    <br>
    <%= link_to libraries_path do %>
        <span>←</span> Назад
        <% end %>