config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'books#index'
  resources :issuances
  resources :books
  resources :libraries
  resources :subscribers
  resources :workers
  get '/summary', to: 'summary#index', as: :summary

end

app/models/issuance.rb
class Issuance < ActiveRecord::Base
  belongs_to :subscriber
  belongs_to :book
  
  validates :book_id, :subscriber_id, :issuance_date, presence: true
  
  def self.current
    where('return_date >= ?', Time.zone.now.beginning_of_day)
  end
end

app/controllers/issuances_controller.rb
class IssuancesController < ApplicationController
  before_action :set_issuance, only: [:show, :edit, :update, :destroy]

  # GET /issuances
  # GET /issuances.json
  def index
    @issuances = Issuance.all
  end

  # GET /issuances/1
  # GET /issuances/1.json
  def show
  end

  # GET /issuances/new
  def new
    @issuance = Issuance.new
  end

  # GET /issuances/1/edit
  def edit
  end

  # POST /issuances
  # POST /issuances.json
  def create
    @issuance = Issuance.new(issuance_params)

    respond_to do |format|
      if @issuance.save
        format.html { redirect_to @issuance, :flash => { success: "Выдача успешно создана"} }
        format.json { render :show, status: :created, location: @issuance }
      else
        format.html { render :new }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issuances/1
  # PATCH/PUT /issuances/1.json
  def update
    respond_to do |format|
      if @issuance.update(issuance_params)
        format.html { redirect_to @issuance, :flash => { success: "Выдача успешно обновлена"} }
        format.json { render :show, status: :ok, location: @issuance }
      else
        format.html { render :edit }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuances/1
  # DELETE /issuances/1.json
  def destroy
    @issuance.destroy
    respond_to do |format|
      format.html { redirect_to issuances_url, :flash => { danger: "Выдача удалена"} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issuance
      @issuance = Issuance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issuance_params
      params.require(:issuance).permit(
        :book_id,
        :subscriber_id,
        :issuance_date,
        :return_date
        )
    end
end

app/helpers/issuances_helper.rb
module IssuancesHelper
end

app/views/issuances/_form.html.erb
<%= form_for(@issuance, html: {class: 'form-horizontal'}) do |f| %>
    <% if @issuance.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@issuance.errors.count, "error") %> prohibited this issuance from being saved:</h2>
            <ul>
                <% @issuance.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>
            <div class="form-group">
                <label for="issuance[name]" class="col-md-2">Книга</label>
                <div class="col-md-4">
                    <%= f.select :book_id, Book.all.collect {|b| [ b.name, b.id ]}, {include_blank: "Выберите книгу"}, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="issuance[name]" class="col-md-2">Абонент</label>
                <div class="col-md-4">
                    <%= f.select :subscriber_id, Subscriber.all.collect {|s| [ fio(s), s.id ]}, {include_blank: "Выберите абонента"}, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="issuance[name]" class="col-md-2">Дата выдачи</label>
                <div class="col-md-4">
                    <%= f.date_field :issuance_date, class: 'form-control input-sm' %>
                </div>
            </div>
            <div class="form-group">
                <label for="issuance[name]" class="col-md-2">Дата возврата</label>
                <div class="col-md-4">
                    <%= f.date_field :return_date, class: 'form-control input-sm' %>
                </div>
            </div>
            <br>
            <div class="actions">
                <%= f.submit "Отправить", class: 'btn btn-sm btn-primary' %>
            </div>
            <% end %>

app/views/issuances/edit.html.erb
<% breadcrumb :edit_issuance, @issuance %>
    <h1>Редактирование выдачи</h1>
    <%= render 'form' %>
        <br>
        <%= link_to @issuance do %>
            <span>←</span> Назад
            <% end %>

app/views/issuances/index.html.erb
<% breadcrumb :issuances %>
    <div class="row">
        <div class="col-md-6">
            <h1>Выдачи</h1>
        </div>
        <div class="col-md-6">
            <div class="pull-right">
                <%= link_to new_issuance_path, class: 'btn btn-primary btn-sm' do %>
                    <i class="fa fa-plus"></i> Новая выдача
                    <% end %>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="table__id">#</th>
                <th>Книга</th>
                <th>Абонент</th>
                <th>Дата выдачи</th>
                <th>Дата возврата</th>
                <th class="table__actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            <% @issuances.each do |issuance| %>
                <tr>
                    <td class="table__id">
                        <%= issuance.id %>
                    </td>
                    <td>
                        <%= issuance.book.name %>
                    </td>
                    <td>
                        <%= fio issuance.subscriber %>
                    </td>
                    <td>
                        <%= issuance.issuance_date %>
                    </td>
                    <td>
                        <%= issuance.return_date %>
                    </td>
                    <td class="table__actions">
                        <%= link_to issuance do %>
                            <i class="fa fa-eye"></i>
                            <% end %>
                                <%= link_to edit_issuance_path(issuance) do %>
                                    <i class="fa fa-pencil"></i>
                                    <% end %>
                                        <%= link_to issuance, method: :delete, data: { confirm: 'Вы уверены?' } do %>
                                            <i class="fa fa-trash"></i>
                                            <% end %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

app/views/issuances/new.html.erb
<% breadcrumb :new_issuance %>
    <h1>Новая выдача</h1>
    <%= render 'form' %>
        <br>
        <%= link_to issuances_path do %>
            <span>←</span> Назад
            <% end %>

app/views/issuances/show.html.erb
<% breadcrumb :issuance, @issuance %>
    <h1>Выдача <%= @issuance.id %></h1>
    <div class="row">
        <label for="issuance[name]" class="col-md-2">Книга</label>
        <div class="col-md-4">
            <%= @issuance.book.name %>
        </div>
    </div>
    <div class="row">
        <label for="issuance[name]" class="col-md-2">Абонент</label>
        <div class="col-md-4">
            <%= fio @issuance.subscriber %>
        </div>
    </div>
    <div class="row">
        <label for="issuance[name]" class="col-md-2">Дата выдачи</label>
        <div class="col-md-4">
            <%= @issuance.issuance_date %>
        </div>
        <div class="row">
        </div>
        <label for="issuance[name]" class="col-md-2">Дата возврата</label>
        <div class="col-md-4">
            <%= @issuance.return_date %>
        </div>
    </div>
    <br>
    <div>
        <%= link_to 'Изменить', edit_issuance_path(@issuance), class: 'btn btn-primary btn-sm' %>
    </div>
    <br>
    <%= link_to issuances_path do %>
        <span>←</span> Назад
        <% end %>