config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'books#index'
  resources :issuances
  resources :books
  resources :libraries
  resources :subscribers
  resources :workers
  get '/summary', to: 'summary#index', as: :summary

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :library
  validates :library_id, :surname, :name, :position, presence: true
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, :flash => { success: "Сотрудник успешно добавлен"} }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, :flash => { success: "Сотрудник успешно обновлен"} }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, :flash => { danger: "Сотрудник удален"} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(
          :library_id,
          :position,
          :surname,
          :name,
          :patronymic,
          :birthday,
          :joined_date,
          :education
        )
    end
end
                    

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(@worker, html: {class: 'form-horizontal'}) do |f| %>
    <% if @worker.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>
            <ul>
                <% @worker.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Библиотека</label>
                <div class="col-md-4">
                    <%= f.select :library_id, Library.all.collect {|l| [ l.name, l.id ]}, {include_blank: "Выберите библиотеку"}, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Должность</label>
                <div class="col-md-4">
                    <%= f.text_field :position, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Фамилия</label>
                <div class="col-md-4">
                    <%= f.text_field :surname, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Имя</label>
                <div class="col-md-4">
                    <%= f.text_field :name, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Отчество</label>
                <div class="col-md-4">
                    <%= f.text_field :patronymic, class: 'form-control input-sm' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Дата рождения</label>
                <div class="col-md-4">
                    <%= f.date_field :birthday, class: 'form-control input-sm' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Дата принятия на работу</label>
                <div class="col-md-4">
                    <%= f.date_field :joined_date, class: 'form-control input-sm' %>
                </div>
            </div>
            <div class="form-group">
                <label for="worker[name]" class="col-md-2">Образование</label>
                <div class="col-md-4">
                    <%= f.text_field :education, class: 'form-control input-sm' %>
                </div>
            </div>
            <br>
            <div class="actions">
                <%= f.submit "Отправить", class: 'btn btn-sm btn-primary' %>
            </div>
            <% end %>

app/views/workers/edit.html.erb
<% breadcrumb :edit_worker, @worker %>
    <h1>Редактирование сотрудника</h1>
    <%= render 'form' %>
        <br>
        <%= link_to @worker do %>
            <span>←</span> Назад
            <% end %>

app/views/workers/index.html.erb
<% breadcrumb :workers %>
    <div class="row">
        <div class="col-md-6">
            <h1>Сотрудники</h1>
        </div>
        <div class="col-md-6">
            <div class="pull-right">
                <%= link_to new_worker_path, class: 'btn btn-primary btn-sm' do %>
                    <i class="fa fa-plus"></i> Новый сотрудник
                    <% end %>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="table__id">#</th>
                <th>ФИО</th>
                <th>Библиотека</th>
                <th>Должность</th>
                <th>Дата рождения</th>
                <th class="table__actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            <% @workers.each do |worker| %>
                <tr>
                    <td class="table__id">
                        <%= worker.id %>
                    </td>
                    <td>
                        <%= fio worker %>
                    </td>
                    <td>
                        <%= worker.library.name %>
                    </td>
                    <td>
                        <%= worker.position %>
                    </td>
                    <td>
                        <%= worker.birthday %>
                    </td>
                    <td class="table__actions">
                        <%= link_to worker do %>
                            <i class="fa fa-eye"></i>
                            <% end %>
                                <%= link_to edit_worker_path(worker) do %>
                                    <i class="fa fa-pencil"></i>
                                    <% end %>
                                        <%= link_to worker, method: :delete, data: { confirm: 'Вы уверены?' } do %>
                                            <i class="fa fa-trash"></i>
                                            <% end %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

app/views/workers/new.html.erb
<% breadcrumb :new_worker %>
    <h1>Новый сотрудник</h1>
    <%= render 'form' %>
        <br>
        <%= link_to workers_path  do %>
            <span>←</span> Назад
            <% end %>

app/views/workers/show.html.erb
<% breadcrumb :worker, @worker %>
    <h1><%= fio @worker %></h1>
    <div class="row">
        <label for="worker[name]" class="col-md-2">Библиотека</label>
        <div class="col-md-4">
            <%= @worker.library.name %>
        </div>
    </div>
    <div class="row">
        <label for="worker[name]" class="col-md-2">Должность</label>
        <div class="col-md-4">
            <%=  @worker.position %>
        </div>
    </div>
    <div class="row">
        <label for="worker[name]" class="col-md-2">ФИО</label>
        <div class="col-md-4">
            <%=  fio @worker %>
        </div>
    </div>
    <div class="row">
        <label for="worker[name]" class="col-md-2">Дата рождения</label>
        <div class="col-md-4">
            <%=  @worker.birthday %>
        </div>
    </div>
    <div class="row">
        <label for="worker[name]" class="col-md-2">Дата принятия на работу</label>
        <div class="col-md-4">
            <%=  @worker.joined_date %>
        </div>
    </div>
    <div class="row">
        <label for="worker[name]" class="col-md-2">Образование</label>
        <div class="col-md-4">
            <%= @worker.education %>
        </div>
    </div>
    <br>
    <div>
        <%= link_to 'Изменить', edit_worker_path(@worker), class: 'btn btn-primary btn-sm' %>
    </div>
    <br>
    <%= link_to workers_path do %>
        <span>←</span> Назад
        <% end %>