config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'books#index'
  resources :issuances
  resources :books
  resources :libraries
  resources :subscribers
  resources :workers
  get '/summary', to: 'summary#index', as: :summary

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :library
  has_many :issuances, dependent: :destroy
  validates :library_id, :ticket, :surname, :name, :address, :tel, presence: true
  validates :ticket, uniqueness: { case_sensitive: true }
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, :flash => { success: "Подписчик успешно добавлен"} }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, :flash => { success: "Подписчик успешно обновлен"} }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, :flash => { danger: "Подписчик удален"} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(
          :library_id,
          :ticket,
          :surname,
          :name,
          :patronymic,
          :address,
          :tel
        )
    end
end


                

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber, html: {class: 'form-horizontal'}) do |f| %>
    <% if @subscriber.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>
            <ul>
                <% @subscriber.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Библиотека</label>
                <div class="col-md-4">
                    <%= f.select :library_id, Library.all.collect {|l| [ l.name, l.id ]}, {include_blank: "Выберите библиотеку"}, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Номер билета</label>
                <div class="col-md-4">
                    <%= f.text_field :ticket, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Фамилия</label>
                <div class="col-md-4">
                    <%= f.text_field :surname, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Имя</label>
                <div class="col-md-4">
                    <%= f.text_field :name, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Отчество</label>
                <div class="col-md-4">
                    <%= f.text_field :patronymic, class: 'form-control input-sm' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Адрес</label>
                <div class="col-md-4">
                    <%= f.text_field :address, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <div class="form-group">
                <label for="subscriber[name]" class="col-md-2">Телефон</label>
                <div class="col-md-4">
                    <%= f.text_field :tel, class: 'form-control input-sm', required: 'required' %>
                </div>
            </div>
            <br>
            <div class="actions">
                <%= f.submit "Отправить", class: 'btn btn-sm btn-primary' %>
            </div>
            <% end %>

app/views/subscribers/edit.html.erb
<% breadcrumb :edit_subscriber, @subscriber %>
    <h1>Редактирование абонента</h1>
    <%= render 'form' %>
        <br>
        <%= link_to @subscriber do %>
            <span>←</span> Назад
            <% end %>

app/views/subscribers/index.html.erb
<% breadcrumb :subscribers %>
    <div class="row">
        <div class="col-md-6">
            <h1>Абоненты</h1>
        </div>
        <div class="col-md-6">
            <div class="pull-right">
                <%= link_to new_subscriber_path, class: 'btn btn-primary btn-sm' do %>
                    <i class="fa fa-plus"></i> Новый абонент
                    <% end %>
            </div>
        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="table__id">#</th>
                <th>ФИО</th>
                <th>Телефон</th>
                <th>Номер билета</th>
                <th>Библиотека</th>
                <th class="table__actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            <% @subscribers.each do |subscriber| %>
                <tr>
                    <td class="table__id">
                        <%= subscriber.id %>
                    </td>
                    <td>
                        <%= fio subscriber %>
                    </td>
                    <td>
                        <%= subscriber.tel %>
                    </td>
                    <td>
                        <%= subscriber.ticket %>
                    </td>
                    <td>
                        <%= subscriber.library.name %>
                    </td>
                    <td class="table__actions">
                        <%= link_to subscriber do %>
                            <i class="fa fa-eye"></i>
                            <% end %>
                                <%= link_to edit_subscriber_path(subscriber) do %>
                                    <i class="fa fa-pencil"></i>
                                    <% end %>
                                        <%= link_to subscriber, method: :delete, data: { confirm: 'Вы уверены?' } do %>
                                            <i class="fa fa-trash"></i>
                                            <% end %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

app/views/subscribers/new.html.erb
<% breadcrumb :new_subscriber %>
    <h1>Новый абонент</h1>
    <%= render 'form' %>
        <br>
        <%= link_to subscribers_path do %>
            <span>←</span> Назад
            <% end %>

app/views/subscribers/show.html.erb
<% breadcrumb :subscriber, @subscriber %>
    <h1><%= fio @subscriber %></h1>
    <div class="row">
        <label for="subscriber[name]" class="col-md-2">Библиотека</label>
        <div class="col-md-4">
            <%=  @subscriber.library.name %>
        </div>
    </div>
    <div class="row">
        <label for="subscriber[name]" class="col-md-2">Номер билета</label>
        <div class="col-md-4">
            <%=  @subscriber.ticket  %>
        </div>
    </div>
    <div class="row">
        <label for="subscriber[name]" class="col-md-2">ФИО</label>
        <div class="col-md-4">
            <%=  fio @subscriber %>
        </div>
    </div>
    <div class="row">
        <label for="subscriber[name]" class="col-md-2">Адрес</label>
        <div class="col-md-4">
            <%=  @subscriber.address  %>
        </div>
    </div>
    <div class="row">
        <label for="subscriber[name]" class="col-md-2">Телефон</label>
        <div class="col-md-4">
            <%=  @subscriber.tel  %>
        </div>
    </div>
    <br>
    <div>
        <%= link_to 'Изменить',  edit_subscriber_path(@subscriber), class: 'btn btn-primary btn-sm' %>
    </div>
    <br>
    <%= link_to subscribers_path do %>
        <span>←</span> Назад
        <% end %>